# Generated by Django 4.2.29 on 2026-04-02 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('demo', 'Демо'), ('recording', 'В записи'), ('mixing', 'На сведении'), ('mastering', 'На мастеринге'), ('done', 'Готов')], default='demo', max_length=20)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='projects.project')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('version_comment', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='tracks.track')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_audio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('track', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AudioComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp_seconds', models.IntegerField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracks.audiofile')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp_seconds'],
            },
        ),
    ]
